version: '3'
networks:
  dpd2:
    driver: bridge

services:

  php:
    container_name: myphp
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports: 
      - 9000:9000
    volumes: 
      - ./www/:/var/www/html/
    tty: true
    networks: 
      - dpd2
  
  nginx:
    image: nginx
    container_name: nginx-w
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
      - ./www:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
    tty: true
    networks:
      - dpd2
  
  mysql:
    image: mysql:5.7.22
    container_name: mysql-w
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwerdf
      TZ: Asia/Shanghai
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - dpd2
   
  composer:
    image: composer
    privileged: true
    container_name: composer-w
    volumes:
      - ./www:/app
    command: composer create-project topthink/think=5.1.* tp5 
    networks: 
      - dpd2
